#
# Run For Money v2
# by SNWCreations (B站: @ZX夏夜之风)
#
# 主配置文件
#

# !!!!!!!!! 注意 !!!!!!!!!
# 请一定要按需修改下面的配置!

# 哪个世界将被用作游戏？安装了多世界插件的服务器可能需要此项。
# 默认为 world 。有效值为字符串
game_world: "world"

# 猎人释放时间，以秒为单位，遇到无效值时默认 60 秒。
hunter_release_time: 60
# 游戏总时长，以分钟为单位，遇到无效值时默认 30 分钟。
game_time: 30
# 终止间的位置，格式 x y z
# 遇到无效值时会发出警告并忽略配置项，游戏时玩家被淘汰但没有可用的终止间的位置时，玩家将会在被淘汰的位置成为旁观者。
end_room: ""
# 每秒获得的硬币的数量，遇到无效值时默认使用 100/秒。
coin_per_second: 100
# 当逃走队员被捕时，当时拥有的B币该乘以几？默认值为 0.1 (即 1/10) 。
coin_multiplier_on_be_caught: 0.1

####### ------------ 物品配置 ------------ #######

# 猎人暂停卡有效时间，单位: 秒，默认值: 3 秒。
hpc_time: 3

# 弃权镐可以挖掉的方块。遇到无效值时，默认为钻石块。
exiting_pickaxe_target_block: "minecraft:diamond_block"

# 抗性卡的有效时间，单位: 秒，默认值: 5 秒
ignore_time: 5
